# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/.Xil/Vivado-13824-LAPTOP-OMJ07UF3/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/imports/Downloads/FF.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/ascii.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/imports/Downloads/debouncer.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/delay.vhd
      D:/Uni/Semester4/Project/WIP/fifo_test_2_send/fifo_test_2.srcs/sources_1/new/ram_8by32.vhd
      D:/Uni/Semester4/Project/WIP/fifo_test_2/fifo_test_2.srcs/sources_1/new/fifo_w_signal_control.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/oled_ctrl.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/oled_ex.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/oled_init.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/spi_ctrl.vhd
      D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/Oled_boyy.srcs/sources_1/new/fifo_oled_connection.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top fifo_oled_connection
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/Uni/Semester4/Project/WIP/Fifo_to_oled/Oled_boyy/.Xil/Vivado-13824-LAPTOP-OMJ07UF3/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
