set_property PACKAGE_PIN AA9 [get_ports {pin_adc[1]}]
set_property PACKAGE_PIN Y11 [get_ports {pin_adc[0]}]
set_property PACKAGE_PIN Y10 [get_ports adc_d1]
set_property PACKAGE_PIN R16 [get_ports b_s]
set_property PACKAGE_PIN T18 [get_ports c_btn]
set_property PACKAGE_PIN T22 [get_ports c_led]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN U10 [get_ports oled_dc]
set_property PACKAGE_PIN U9 [get_ports oled_res]
set_property PACKAGE_PIN AB12 [get_ports oled_sclk]
set_property PACKAGE_PIN AA12 [get_ports oled_sdin]
set_property PACKAGE_PIN U11 [get_ports oled_vbat]
set_property PACKAGE_PIN U12 [get_ports oled_vdd]
set_property PACKAGE_PIN P16 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_adc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_adc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_d1]
set_property IOSTANDARD LVCMOS33 [get_ports b_s]
set_property IOSTANDARD LVCMOS33 [get_ports c_btn]
set_property IOSTANDARD LVCMOS33 [get_ports c_led]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_dc]
set_property IOSTANDARD LVCMOS33 [get_ports oled_res]
set_property IOSTANDARD LVCMOS33 [get_ports oled_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_sdin]
set_property IOSTANDARD LVCMOS33 [get_ports oled_vbat]
set_property IOSTANDARD LVCMOS33 [get_ports oled_vdd]
set_property IOSTANDARD LVCMOS33 [get_ports rst]



set_property PACKAGE_PIN T21 [get_ports signal_led]
set_property IOSTANDARD LVCMOS33 [get_ports signal_led]

set_property PACKAGE_PIN N15 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property PACKAGE_PIN R18 [get_ports spacebar]
set_property IOSTANDARD LVCMOS33 [get_ports spacebar]
