# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/.Xil/Vivado-27012-DESKTOP-K0VOKNT/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.cache/wt} [current_project]
set_property parent.project_path {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo {c:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/Downloads/FF.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/ascii.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/Downloads/debouncer.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/sources_1/imports/SPRO4/debouncer.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/delay.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/sources_1/imports/SPRO4/dit_dah.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/Raul/Downloads/ram_8by32.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/fifo_oled_connection.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/fifo_w_signal_control.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/oled_ctrl.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/oled_ex.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/oled_init.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/sources_1/imports/SPRO4/pmod_adc.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/pulse_stable_conversion.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/sources_1/imports/SPRO4/signal_debouncer.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/spi_ctrl.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/timer_variable.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/sources_1/imports/new/translation_interface.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/imports/sources_1/new/v2.vhd}
  {C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/sources_1/new/mejn.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/constrs_1/new/Mejn_const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/peter/Desktop/Elec Bsc/4th semester/SPRO4/Fifo_to_oled_v3/Oled_boyy/Oled_boyy.srcs/constrs_1/new/Mejn_const.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mejn -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mejn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mejn_utilization_synth.rpt -pb mejn_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
